### ISSUE TITLE
完美解决移动端使用 rem 单位时 CSS Sprites 错位问题 

### ISSUE THREAD

**Issue by banricho** [banricho/webLog#1]
移动端网页开发离不开强大的 `rem` 支持，但由于各尺寸基数未必成比例，以及浏览器的计算偏差，常常会导致 `background-position` 不够精确，引发 CSS Sprites 错位。下图左侧为 PC 端模拟页面，右侧为移动端实测：

![错位对比][1]

明显可以看出右侧的图标已经错位，图中的问题可以依赖 iconfont 解决，但只局限于单色图标。既要响应式，又得避免 `rem` 带来的问题，选用百分比是个好方案。

可是……等等，怎么还是错位？甚至完全没办法定位到需要的位置？原来 `backgroud-positon` 为百分比单位时，其计算方式非常特殊，这里引用 林小志 在 [《闲扯 background-position 的单位属性值》][2] 中的一段话：

> 似乎大概意思是：如果是 14% 84% 的这个值，那么就以图片的 14% 84% 的坐标点，放置在容器的 14% 84% 的位置。那这样理解的话，就是说明，如果是用百分比来作为 background-position 的属性值的话，那么背景图片相对于容器的中心点是随时都在改变的。

于是问题迎刃而解，我们可以整理出以下公式：

```
n%*W - n%*w = -x
n%*H - n%*h = -y
```

其中 `W/H` 是整个雪碧图的宽高， `w/h` 是单个 icon 的大小，而 `x/y` 则是传统的 `px` 坐标。基于 gulp.spritesmith + Sass，使用以下模板：

```
{{#extend "scss"}}
{{#content "sprites"}}
{{#each sprites}}
@mixin {{prefix}}-{{name}} {
    background-position: 0 {{offset_y}}/({{height}}-{{total_height}})*100%;
}

{{/each}}
{{/content}}
{{#content "spritesheet"}}
.{{spritesheet.name}} {
    background-image: url('{{{spritesheet.escaped_image}}}');
    background-repeat: no-repeat;
    background-size: px({{spritesheet.width}}) px({{spritesheet.height}});
}
{{/content}}
{{/extend}}
```

其中的 `px(*)` 是一个将 `px` 转换为 `rem`的函数，`{{prefix}}` 等变量可以在 [gulpfile.js][4] 中配置。之所以用 `@mixin`，是由于 CSS3 动画中可以使用 `@include` 但不能使用 `@extend`。同时也兼顾了元素与伪元素混合使用的情况，避免产生多余的样式。

![最终效果][3]

怎么样？完美解决了吧 :)

（完）

[1]: http://cdn.brdev.org/github/pic1.jpg
[2]: http://linxz.github.io/blog/css%E5%B1%9E%E6%80%A7%E5%9F%BA%E7%A1%80/2015/09/talk-about-background-position-values.html
[3]: http://cdn.brdev.org/github/pic2.jpg
[4]: https://github.com/banricho/SNSH_gulpfile.js/blob/master/gulpfile.js

**Comment by meltifa** [comment]
background-size和background-position都用rem一样可以解决吧？还是说我这个方法会有其他问题？

**Comment by banricho** [comment]
@meltifa 嗯，都用 `rem` 的话就会和上面说的那样，产生错位。

webkit 计算 `rem` 本身就是有 bug 的，加上一些图片的尺寸不能很好的符合根单位，很容易发生错位。目前来看，在 `background-positon` 中使用百分比，在任何时候都是可靠的。

**Comment by zhangXWei** [comment]
我用的rem，并没有遇到错位

**Comment by banricho** [comment]
@zhangXWei 不是所有的时候都会错位

**Comment by snipertulip** [comment]
移动端，分别按照DPR做，就不会有错位，其实就是在不等比的情况下出现的问题

**Comment by qiansen1386** [comment]
可以不用雪碧图啊 :joy: 不是说 http2 不需要雪碧图咩？

**Comment by banricho** [comment]
@qiansen1386 嗯，已经很久不用雪碧图了，偶尔动画的时候用……
这篇文章真的是没有什么时效性了，很久以前的东西。

很多方式可以避免，不光是 % 一种。看来是时候关闭这个 issue 了……

**Comment by mayorhao** [comment]
我遇到了雪碧图在不同手机下适配的问题了，请问是什么原因造成的呢？对您这句不是很理解。
`webkit 计算 rem 本身就是有 bug 的，加上一些图片的尺寸不能很好的符合根单位，很容易发生错位。目前来看，在 background-positon 中使用百分比，在任何时候都是可靠的。
`
另外，还有什么方式可以避免呢。多谢！

**Comment by anrananran** [comment]
我测试了下，在部分安卓机型上仍然有错位问题，和用rem差不多，唉，难道除了svg和iconfont真的没有其他办法解决png sprite图的问题了吗
