### ISSUE TITLE
关于 Vue.js 的一些笔记

### ISSUE THREAD

**Issue by banricho** [banricho/webLog#3]
这段时间中心内在搞前后端分离，大体就是利用一些 MVVM 框架以及 RAP 等工具，让前端脱离后端进行开发，以及避免转制 Freemarker 模板带来的一系列合作问题。每次为了解决问题而引入新的东西，一般都会带来新的问题：

1. 前端工程师对于业务逻辑不太熟悉，导致前期花费较多的时间，并且无法合理的预估开发时长。
2. 前端工程师的工作量变大了，但并没有获得足够的时间，因此需要与产品经理、管理人员进行沟通并获得理解。
3. 相比以前，产品需求、后端接口等信息的变动更需要及时的通知到前端。
4. 后端工程师不能撒手不管，如果能够封装好一部分逻辑，合作将会更愉快。

针对第 4 点，打个比方。比如某分类下的商品含有上架、下架的状态，用户可对分类进行显示、隐藏和删除的操作。业务要求隐藏分类时，该分类下不得有上架商品，而删除分类时，该分类下不得有商品。在目前我所做的项目里，后端提供的是单个分类的查询接口，可查询该分类下商品的上架和下架数量，在执行隐藏操作时，我需要读取该分类信息，判断其中的上架数量是否为 0，而删除该分类时，判断其中的上架和下架数量是否均为 0。这里只是举个例子，因为服务端本身也应该有判断，所以直接返回 yes or no 的结果会大大减轻前端工程师的工作量，让合作更愉快。

好像有些偏题了，嗯，在选择 MVVM 框架时，我们的 PC 产品线使用的是 Avalon.js 以满足兼容低版本 IE 的需求，而移动端产品线（包含 Pad 端收银机）使用的是 Vue.js。

**Comment by banrikun** [comment]
使用 Vue.js 很方便，只需要 `new` 一个 Vue 实例即可：

```
new Vue({
    el: '#demo',
    data: {
        message: 'Hello Vue.js!'
    }
})
```

为了能够在 Vue 实例外部读取到数据，一般来说都会将其赋值给一个变量。在 Vue 实例内部，`el` 是一个 querySelector 选择器，所以即使是相同 .class 的多个元素，也只有第一个有效。`data` 保存着该 Vue 实例中的原始静态数据，如果需要对数据进行单次计算，可以在 HTML 中直接操作，多次计算则需要写在 `computed` 中，比如：

```
computed: {
    showMasker: function() {
        var masker = this.showEditSort || this.showTip || this.showAsk;
        return masker;
    }
}
```

还有个常用的属性 `methods` 可用来添加事件监听，在 HTML 标签内加上类似 `v-on="click: fun"` 即可。（回家吃饭了，先不更了……）

**Comment by banrikun** [comment]
MVVM 框架和原本类 jQuery 库最大的区别就是使用数据去驱动视觉层，所以需要转变使用思想，避开直接操作 DOM，而是将 DOM 的行为与数据绑定，通过操作数据来操作 DOM。

拿常用的 `v-on` 举例：

```
<div class="pm-masker" v-show="showMasker"></div>
```

当 `showMasker` 为 `false` 时，Vue.js 会自动添加 `style="display: none"`，而为 `true` 时，则什么都不添加。这点和 jQuery 有些区别，因为 jQuery 会检测元素原本该有的 `display` 值，所以即使你在 CSS  中 `display: none`了，也可以被 `show()` 出来，但是 Vue.js 却不能。

**Comment by banrikun** [comment]
在 Vue.js 中，过滤器也是一个很强大的功能。其实质是一个函数，根据所传入的参数，返回过滤后的值。过滤器使用 `|` 标记，可直接写在指令后的引号内部：

```HTML
<ul id="demo">
    <li v-repeat="list | filterBy searchKey in 'left' ">{{left}} - {{right}}</li>
</ul>
```

上述环境中，Vue.js 会在 `left` 属性中查找包含 `searchKey` 的值，并仅渲染符合条件的部分。其中的 `searchKey` 是在 `data` 中的一个值，如果此时值为 `o` 时，则不会渲染 `hi - vue` 这一组数据。当 `searchKey` 为空时，则不会进行任何过滤操作。

此功能可用于实现列表中按条件筛选功能，在不需要加载多余数据的情况下，减少对后端的请求和接口依赖。实际上过滤器还内置了很多方法，并可用于大部分指令中，建议阅读[官方文档][1]。

[1]:http://cn.vuejs.org/api/filters.html

**Comment by banrikun** [comment]
查漏补缺：

在调试过程中发现，页面加载瞬间总是出现很多“一闪而过”的画面，这是因为 Vue 还没有完成数据渲染，使得一些元素没有被隐藏。为此，Vue 提供了一个空指令 `v-cloak`，它将在 VM 编译结束时被移除。

借此，我们可以通过 CSS 来隐藏未被编译好的部分：

```CSS
[v-cloak] {
    visibility: hidden;
}
```

当然，`display: none` 也是可行的。

**Comment by banrikun** [comment]
忙碌的双 11 就要结束了，Vue 也发布了好多个新版本（…），API 经历了一些变动。

**Comment by banrikun** [comment]
今天修复了一处 bug，要被自己蠢哭了，特此警示众人。

场景：给列表添加了过滤器功能，可以筛选显示符合条件的子元素。同时列表中的子元素可以被编辑，而编辑操作依赖传参 `$index`。

引发问题：在筛选形态时产生了操作错位，比如对 `list[0]` 操作实际上改动的是 `list[1]`，因为在过滤时 `$index` 发生了改变，但只能对原本的 `$index` 进行操作。所以针对带有数据交互的列表时，一定要避开依赖 `$index` 进行操作。

>`$index`在操作的时候是不可靠的，稍微哪里变一下，就坑死自己了。　　—— @民工精髓V

**Comment by banrikun** [comment]
今天被测出一个样式错位 bug，很明显是低版本 webkit 内核浏览器不识别非私有属性造成的。其根本原因还是我的写法不正确，导致 Vue 没有能够正确侦测到样式的属性名，无法自动添加 prefix。

有问题的写法：

```JS
computed: {
    nowProcess: function() {
        var text = (this.mode === '7') ? 'b' : 'n';

        return {
            name: getProcess(this.washStep)[text],
            style: 'transform: translateX(' + getProcess(this.washStep)['x'] + 'rem)'
        }
    }
}
```

修正写法：

```JS
computed: {
    nowProcess: function() {
        var text = (this.mode === '7') ? 'b' : 'n';

        return {
            name: getProcess(this.washStep)[text],
            style: {
                transform: 'translateX(' + getProcess(this.washStep)['x'] + 'rem)'
            }
        }
    }
}
```

所以，千万要避免将样式的属性名包裹在字符串中，这样会使得 Vue 无法检测到，也就不能自动添加私有属性前缀了。

**Comment by zhibuzu** [comment]
写的很好！↖(^ω^)↗

**Comment by godlikedeveloper** [comment]
学习了
