### ISSUE TITLE
JavaScript 中的一些重要特性

### ISSUE THREAD

**Issue by banricho** [banricho/webLog#4]
前段时间翻到一本书，书后的附录讲解了 JavaScript 中的一些难点和特性。看完后觉得写的不错，就准备开个 issue 记录下来。谁知道一整理却发现好多模糊不清的地方，就不停的查资料、理解以及写 demo 验证。就这样越写越长，改了好几版，和读书笔记也离的越来越遥远了……

于是这个 issue 就在不断的改名、换 tag 中增加了一圈又一圈的黑历史……

**Comment by banrikun** [comment]
看了一部分《JavaScript DOM 高级程序设计》，另外补充看了一下《jQuery技术内幕》。

看着讲解也不太看得懂源码，晕晕的……心好累

**Comment by banrikun** [comment]
昨天又看了一部分《JavaScript DOM 高级程序设计》，犯困就去看了会儿慕课网的视频……

今天回去整理下书桌再看书，坐床上简直 =..=

**Comment by banrikun** [comment]
前两周双 11 太忙了，经常熬夜甚至通宵，于是也没空看书。

然后这段时间实践了几个基于 Vue 的项目，也抽空写了几个 demo，补习了一些 1.0 的 API。

周末把之前弃坑的《JavaScript 深入浅出》系列视频看完了。

————————————

看了一会儿算法，有点晕，先晾着看别的 = = 嗯没 CS 专业的基础确实有点头大。慢慢来吧。

————————————

周末去参加了 iWeb 峰会，感受了别人公司的氛围，确实是咱们这里比不上的。最近公司的一些制度变化，以及越来越多的同事跑路，让我也起了这个心思吧。

不过现在只有不到半年的经验，也水平也不太够，所以剩下的时间一定要沉下心来多学一些东西。单身狗毫无牵挂，去哪都是敲代码，选择一个能让自己成长并且不会压抑的环境吧。

**Comment by banricho** [comment]
### 作用域

ES5 没有块级作用域，其作用域由函数来决定。

变量搜索由内部逐渐向外部查找。

`var` 定义的函数 / 变量会被提升，但提升时不会被初始化。

作用域嵌套关系在定义时就被确定，而不是在运行时。

避免隐式定义全局变量。

**Comment by banricho** [comment]
### 闭包

从我的理解来看：A 函数包含并返回了 B 函数，由于作用域设定，B 函数可以读取到 A 函数中的私有变量。

```JS
var outter = function() {
    var num = 0;
    var inner = function() {
        num++;
        return num;
    }
    return inner;
}
```

此时，执行 `outter()` 返回的是 `inner` 函数，如果要返回 `num` 的值则需要执行 `outter()()`。不过无论执行多少次 `outter()()`，返回的 `num` 值永远都是 1，所以这还不能算构成一个闭包。

这时我们将 `outter` 的结果赋值，再多次执行它。

```
var fn = outter();

fn();
fn();
fn();
```

会发现返回的 `num` 值每次都会变大，说明其在 `outter` 函数执行后没有被立即释放，而是始终在内存中。这种情况下，就可以称 `inner` 函数是 `outter` 函数的一个闭包，它由 `innner` 函数本身和其环境作用域中的变量 `num` 组成。

**Comment by banricho** [comment]
### this

this 是 JavaScript 中一个非常重要的概念，需要铭记一点： this 始终指向调用**其所在函数**的那个**对象**。

**Comment by banricho** [comment]
### 原型

严格来说，JavaScript 中没有类的概念，ES6 中引入的 `Class` 本质上也是基于原型的语法糖。
